package ua.lsi.media_tracker.enums;

/**
 * Created by LSI on 28.03.2016.
 *
 * @author LSI
 */
public enum MessageCode {
    AUTO_LOAD_DISABLED,
    AUTO_LOAD_UNSUCCESSFUL,
    AUTO_LOAD_SUCCESSFUL,
    LOAD_UNSUCCESSFUL,
    LOAD_SUCCESSFUL,
    SAVE_UNSUCCESSFUL,
    SAVE_SUCCESSFUL,
    SAVE_NOT_SAVED,
    SAVE_ERROR,
    PROPERTIES_FILE,
    SETTINGS_SAVED,
    SETTINGS_NOT_SAVED,
    DEFAULT_SECTION,
    LOAD_SQLITE_SUCCESSFUL,
    LOAD_SQLITE_UNSUCCESSFUL,
    SAVE_SQLITE_SUCCESSFUL,
    SAVE_SQLITE_UNSUCCESSFUL
}
